config/routes.rb
Rails.application.routes.draw do
  namespace :portal do
    resources :offers
    root 'offers#index'
  end
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portal.rb
module Portal
  def self.table_name_prefix
    'portal_'
  end
end

app/models/portal/offer.rb
class Portal::Offer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    datetime = Time.now
    offers = Portal::Offer.where("starts_at <= '#{datetime}'" + "AND ends_at >= '#{datetime}'").order(premium: :desc)
    
    gon.offers = offers
  end
end

app/controllers/portal/offers_controller.rb
class Portal::OffersController < ApplicationController
  before_action :set_portal_offer, only: [:show, :edit, :update, :destroy]
  layout 'portal'

  # GET /portal/offers
  # GET /portal/offers.json
  def index
    @portal_offers = Portal::Offer.all
  end

  # GET /portal/offers/1
  # GET /portal/offers/1.json
  def show
  end

  # GET /portal/offers/new
  def new
    @portal_offer = Portal::Offer.new
  end

  # GET /portal/offers/1/edit
  def edit
  end

  # POST /portal/offers
  # POST /portal/offers.json
  def create
    @portal_offer = Portal::Offer.new(portal_offer_params)

    respond_to do |format|
      if @portal_offer.save
        format.html { redirect_to @portal_offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @portal_offer }
      else
        format.html { render :new }
        format.json { render json: @portal_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portal/offers/1
  # PATCH/PUT /portal/offers/1.json
  def update
    respond_to do |format|
      if @portal_offer.update(portal_offer_params)
        format.html { redirect_to @portal_offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal_offer }
      else
        format.html { render :edit }
        format.json { render json: @portal_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portal/offers/1
  # DELETE /portal/offers/1.json
  def destroy
    @portal_offer.destroy
    respond_to do |format|
      format.html { redirect_to portal_offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portal_offer
      @portal_offer = Portal::Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portal_offer_params
      params.require(:portal_offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium)
    end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  layout 'portal'
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portal/offers_helper.rb
module Portal::OffersHelper
    def status(event)
        datetime = Time.now.localtime.to_datetime

        starts = event.starts_at.localtime.to_datetime

        if event.ends_at.present?
            ends = event.ends_at.localtime.to_datetime

            
            if datetime >= starts  && datetime < ends
                status = 'enabled'
            else
                status = 'disabled'

            end

        else
            status = 'enabled'
        end


        status
    
    end
    
end

app/views/home/index.html.erb
<h1>Top Offers</h1>
<div id='home_vue_app'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashback</title>
    <%= Gon::Base.render_data %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

        <%= stylesheet_packs_with_chunks_tag 'application', 'home_vue', media: 'all' %>
      <%= javascript_packs_with_chunks_tag 'application', 'home_vue', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="content">
            <%= yield %>
            </div>
  </body>
</html>

app/views/layouts/portal.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal || Cashback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="preconnect" href="https://en.gravatar.com" crossorigin>
        <link rel="preconnect" href="https://i.picsum.photos" crossorigin>
        <link rel="dns-prefetch" href="https://en.gravatar.com">
        <link rel="dns-prefetch" href="https://i.picsum.photos">
        <%= stylesheet_packs_with_chunks_tag 'application', media: 'all' %>
        <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="hold-transition sidebar-mini">
        <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" data-turbolinks="false"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <%= link_to 'Home', portal_root_path, class: 'nav-link' %>
            </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
                </div>
            </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="https://picsum.photos/128" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        Brad Diesel
                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Call me whenever you can...</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="https://picsum.photos/7" alt="User Avatar" class="img-size-50 img-circle mr-3">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        M Ninaut
                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">I got your message bro</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                    <img src="https://picsum.photos/128" alt="User Avatar" class="img-size-50 img-circle mr-3">
                    <div class="media-body">
                        <h3 class="dropdown-item-title">
                        Nora Silvester
                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">The subject goes here</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                    </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
                class="fas fa-th-large"></i></a>
            </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link" >
         
            <span class="brand-text font-weight-light">Le Cashback</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                <img src="https://en.gravatar.com/userimage/9923380/0fc16a82ac7453155454124befd56ea4.jpeg" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                <a href="https://mninaut.com" target="_blank" class="d-block">M Ninaut</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Dashboards
                        <i class="right fas fa-angle-left"></i>
                    </p>
                    </a>
                    <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <%= link_to portal_offers_path, class: 'nav-link' do %>
                        <i class="far fa-circle nav-icon"></i>
                        <p>Offers</p>
                        <% end %>
                    </li>
                    </ul>
                </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark jt-title"><%= yield(:title) || 'Starter Page' %></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                    </ol>
                </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
            <%= yield %>
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
            <h5>Title</h5>
            <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2020 <a href="https://mninaut.com">Matheus Ninaut</a>.</strong> All rights
            reserved.
        </footer>
        </div>
    </body>
</html>

app/views/portal/index.html.erb
<h1>Portal#index</h1>
<p>Find me in app/views/portal/index.html.erb</p>


<div id='hello_vue_app'></div>

app/views/portal/offers/_form.html.erb
<%= form_with(model: portal_offer, local: true) do |form| %>
  <% if portal_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portal_offer.errors.count, "error") %> prohibited this portal_offer from being saved:</h2>

      <ul>
        <% portal_offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :advertiser_name %>
    <%= form.text_field :advertiser_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portal/offers/edit.html.erb
<h1>Editing Portal Offer</h1>

<%= render 'form', portal_offer: @portal_offer %>

<%= link_to 'Show', @portal_offer , class: 'btn'%> |
<%= link_to 'Back', portal_offers_path, class: 'btn' %>

app/views/portal/offers/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead  class="thead-dark">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th>Status</th>

      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @portal_offers.each do |portal_offer| %>
      <tr>
        <td><%= portal_offer.id %></td>
        <td><%= portal_offer.advertiser_name %></td>
        <td><%= link_to portal_offer.url, portal_offer.url%></td>
        <td><%= portal_offer.description %></td>
        <td><%= status(portal_offer) %></td>
      
        <td><%= link_to 'Show', portal_offer %></td>
        <td><%= link_to 'Edit', edit_portal_offer_path(portal_offer) %></td>
        <td><%= link_to 'Destroy', portal_offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portal Offer', new_portal_offer_path, class: 'btn btn-primary' %>

app/views/portal/offers/new.html.erb
<%= render 'form', portal_offer: @portal_offer %>

<%= link_to 'Back', portal_offers_path, class: 'btn' %>

app/views/portal/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Advertiser name:</strong>
  <%= @portal_offer.advertiser_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @portal_offer.url, @portal_offer.url%>
  
</p>

<p>
  <strong>Description:</strong>
  <%= @portal_offer.description %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @portal_offer.starts_at.to_formatted_s(:short) %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @portal_offer.ends_at.to_formatted_s(:short) %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @portal_offer.premium %>
</p>

<%= link_to 'Edit', edit_portal_offer_path(@portal_offer), class: 'btn'%> |
<%= link_to 'Back', portal_offers_path, class: 'btn' %>